// apps/react-todo/src/app/app.tsx
import React, {useState} from "react";
import {Task} from "./models/task";

function App() {
  const [value, setValue] = React.useState("");
  const [todos, setTodos] = useState<Array<Task>>([{id: 0, name: 'Starting Item'}]);

  const addTodo = (name: string): void => {
    const newTodos: any = [...todos, {name}];
    setTodos(newTodos);
  }

  const removeTodo = (index: number): void => {
    const newTodos = [...todos]
    newTodos.splice(index, 1)
    setTodos(newTodos);
  }

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!value) return;
    addTodo(value);
    setValue("");
  };

  const add50k = ():void => {
    const newTodos: any = [...todos, {name}];
    let i = 50000
    while (i > 0) {
      newTodos.push({id:i, name:'adding item'});
      i--;
    }
    setTodos(newTodos);
  }

  return (
    <div>
      <h2>Hello React TS!</h2>
      <form onSubmit={handleSubmit}>
        <input type="text" className="input" value={value} onChange={e => setValue(e.target.value)}/>
      </form>
      <button onClick={add50k}>Add 50,000 Todos</button>
      <ul>
        {todos.map((todo, index) => (
          <li>
            {todo.name}
            <button onClick={() => removeTodo(index)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;

// apps/angular-todo/src/app/app.component.ts
import {Component} from '@angular/core';
import {Task} from './models/task'
import {FormBuilder} from '@angular/forms';

@Component({
  selector: 'labs-root',
  template: `
    <div>
      <h2>Hello Angular</h2>
      <form [formGroup]="todoForm" (ngSubmit)="addTask()">
        <input formControlName="name">
      </form>
      <button (click)="add50k()">Add 50,000 Todos</button>
      <ul>
        <li *ngFor="let task of tasks; index as i">
          {{task.name}}
          <button (click)="removeTodo(i)">Delete</button>
        </li>
      </ul>
    </div>
  `,
  styles: [],
})

export class AppComponent {
  title = 'angular-todo';
  tasks: Array<Task> = [{
    id: 0,
    name: 'Starting Item'
  }];

  todoForm = this.formBuilder.group({
    id: '',
    name: ''
  })

  constructor(private formBuilder: FormBuilder) {
  }

  addTask(): void {
    this.tasks.push(this.todoForm.value)
    this.todoForm.reset()
  }

  add50k(): void {
    let i = 50000
    while (i > 0) {
      this.tasks.push({id:i, name:'adding item'});
      i--;
    }
  }

  removeTodo(index: number): void {
    this.tasks.splice(index, 1)
  }
}

<div>
  <h2>Hello Angular</h2>
  <form [formGroup]="todoForm" (ngSubmit)="addTask()">
    <input formControlName="name">
    <button type="submit">Add a task</button>
  </form>
  <ul>
    <li *ngFor="let task of tasks; index as i">
      {{task.name}}
      <button (click)="removeTodo(i)">Delete</button>
    </li>
  </ul>
</div>
